// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AppleHealthPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AppleHealthPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AppleHealthPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsAppleHealthMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsAppleHealthMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsAppleHealthMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashAppleHealthMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashAppleHealthMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashAppleHealthMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum AppleHealthDataType: Int {
  case steps = 0
  case heartRate = 1
  case activeEnergyBurned = 2
  case sleepAnalysis = 3
  case heartRateVariability = 4
  case workout = 5
  case workoutRoute = 6
  case distanceWalkingRunning = 7
  case distanceCycling = 8
  case runningSpeed = 9
  case cyclingCadence = 10
  case cyclingPower = 11
  case weight = 12
  case bloodPressure = 13
}

enum AppleHealthAuthorizationResult: Int {
  case success = 0
  case notAvailable = 1
  case error = 2
}

/// Whether HealthKit would present its authorization sheet for the given read
/// types — i.e. whether the app has ever requested them. Maps
/// `HKAuthorizationRequestStatus`. NOTE: for read types HealthKit deliberately
/// never reports granted-vs-declined, so this distinguishes only
/// "never requested" ([shouldRequest]) from "already requested at least once"
/// ([unnecessary]).
enum AppleHealthReadRequestStatus: Int {
  /// The app has already requested authorization for these read types, so no
  /// further request is necessary. (Does NOT imply the user granted access —
  /// HealthKit hides read grants.)
  case unnecessary = 0
  /// The app has never requested authorization for these read types — the host
  /// should present the authorization flow.
  case shouldRequest = 1
  /// HealthKit could not determine the status (or HealthKit is unavailable).
  case unknown = 2
}

enum AppleHealthSleepStageType: Int {
  case awake = 0
  case light = 1
  case deep = 2
  case rem = 3
}

enum WorkoutActivityType: Int {
  case running = 0
  case walking = 1
  case cycling = 2
  case hiking = 3
  case swimming = 4
  case yoga = 5
  case strength = 6
  case hiit = 7
  case dance = 8
  case badminton = 9
  case basketball = 10
  case football = 11
  case tennis = 12
  case cricket = 13
  case volleyball = 14
  case tableTennis = 15
  case jumpRope = 16
  case meditation = 17
  case pilates = 18
  case elliptical = 19
  case rowing = 20
  case stairClimber = 21
  case boxing = 22
  case kickboxing = 23
  case martialArts = 24
  case handball = 25
  case hockey = 26
  case baseball = 27
  case rugby = 28
  case surfing = 29
  case paddleSports = 30
  case downhillSkiing = 31
  case snowboarding = 32
  case crossCountrySkiing = 33
  case skatingSports = 34
  case golf = 35
  case crossTraining = 36
  case coreTraining = 37
  case waterPolo = 38
  case stretching = 39
  case waterFitness = 40
  case other = 41
}

enum LocationType: Int {
  case indoor = 0
  case outdoor = 1
  case unknown = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppleHealthAuthorizationResponse: Hashable {
  var result: AppleHealthAuthorizationResult
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppleHealthAuthorizationResponse? {
    let result = pigeonVar_list[0] as! AppleHealthAuthorizationResult
    let errorMessage: String? = nilOrValue(pigeonVar_list[1])

    return AppleHealthAuthorizationResponse(
      result: result,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      result,
      errorMessage,
    ]
  }
  static func == (lhs: AppleHealthAuthorizationResponse, rhs: AppleHealthAuthorizationResponse) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthStatistics: Hashable {
  var startTimestamp: Int64
  var endTimestamp: Int64
  var sum: Double? = nil
  var average: Double? = nil
  var min: Double? = nil
  var max: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthStatistics? {
    let startTimestamp = pigeonVar_list[0] as! Int64
    let endTimestamp = pigeonVar_list[1] as! Int64
    let sum: Double? = nilOrValue(pigeonVar_list[2])
    let average: Double? = nilOrValue(pigeonVar_list[3])
    let min: Double? = nilOrValue(pigeonVar_list[4])
    let max: Double? = nilOrValue(pigeonVar_list[5])

    return HealthStatistics(
      startTimestamp: startTimestamp,
      endTimestamp: endTimestamp,
      sum: sum,
      average: average,
      min: min,
      max: max
    )
  }
  func toList() -> [Any?] {
    return [
      startTimestamp,
      endTimestamp,
      sum,
      average,
      min,
      max,
    ]
  }
  static func == (lhs: HealthStatistics, rhs: HealthStatistics) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthSample: Hashable {
  var startTimestamp: Int64
  var endTimestamp: Int64
  var value: Double
  var unit: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthSample? {
    let startTimestamp = pigeonVar_list[0] as! Int64
    let endTimestamp = pigeonVar_list[1] as! Int64
    let value = pigeonVar_list[2] as! Double
    let unit = pigeonVar_list[3] as! String

    return HealthSample(
      startTimestamp: startTimestamp,
      endTimestamp: endTimestamp,
      value: value,
      unit: unit
    )
  }
  func toList() -> [Any?] {
    return [
      startTimestamp,
      endTimestamp,
      value,
      unit,
    ]
  }
  static func == (lhs: HealthSample, rhs: HealthSample) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthQueryRequest: Hashable {
  var dataType: AppleHealthDataType
  var startTimestamp: Int64
  var endTimestamp: Int64
  var intervalMinutes: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthQueryRequest? {
    let dataType = pigeonVar_list[0] as! AppleHealthDataType
    let startTimestamp = pigeonVar_list[1] as! Int64
    let endTimestamp = pigeonVar_list[2] as! Int64
    let intervalMinutes: Int64? = nilOrValue(pigeonVar_list[3])

    return HealthQueryRequest(
      dataType: dataType,
      startTimestamp: startTimestamp,
      endTimestamp: endTimestamp,
      intervalMinutes: intervalMinutes
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      startTimestamp,
      endTimestamp,
      intervalMinutes,
    ]
  }
  static func == (lhs: HealthQueryRequest, rhs: HealthQueryRequest) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthStatisticsResponse: Hashable {
  var statistics: [HealthStatistics]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthStatisticsResponse? {
    let statistics = pigeonVar_list[0] as! [HealthStatistics]

    return HealthStatisticsResponse(
      statistics: statistics
    )
  }
  func toList() -> [Any?] {
    return [
      statistics
    ]
  }
  static func == (lhs: HealthStatisticsResponse, rhs: HealthStatisticsResponse) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthSamplesResponse: Hashable {
  var samples: [HealthSample]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthSamplesResponse? {
    let samples = pigeonVar_list[0] as! [HealthSample]

    return HealthSamplesResponse(
      samples: samples
    )
  }
  func toList() -> [Any?] {
    return [
      samples
    ]
  }
  static func == (lhs: HealthSamplesResponse, rhs: HealthSamplesResponse) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SleepSample: Hashable {
  var startTimestamp: Int64
  var endTimestamp: Int64
  var stage: AppleHealthSleepStageType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SleepSample? {
    let startTimestamp = pigeonVar_list[0] as! Int64
    let endTimestamp = pigeonVar_list[1] as! Int64
    let stage = pigeonVar_list[2] as! AppleHealthSleepStageType

    return SleepSample(
      startTimestamp: startTimestamp,
      endTimestamp: endTimestamp,
      stage: stage
    )
  }
  func toList() -> [Any?] {
    return [
      startTimestamp,
      endTimestamp,
      stage,
    ]
  }
  static func == (lhs: SleepSample, rhs: SleepSample) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SleepQueryRequest: Hashable {
  var startTimestamp: Int64
  var endTimestamp: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SleepQueryRequest? {
    let startTimestamp = pigeonVar_list[0] as! Int64
    let endTimestamp = pigeonVar_list[1] as! Int64

    return SleepQueryRequest(
      startTimestamp: startTimestamp,
      endTimestamp: endTimestamp
    )
  }
  func toList() -> [Any?] {
    return [
      startTimestamp,
      endTimestamp,
    ]
  }
  static func == (lhs: SleepQueryRequest, rhs: SleepQueryRequest) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SleepSamplesResponse: Hashable {
  var samples: [SleepSample]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SleepSamplesResponse? {
    let samples = pigeonVar_list[0] as! [SleepSample]

    return SleepSamplesResponse(
      samples: samples
    )
  }
  func toList() -> [Any?] {
    return [
      samples
    ]
  }
  static func == (lhs: SleepSamplesResponse, rhs: SleepSamplesResponse) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BloodPressureSample: Hashable {
  var startTimestamp: Int64
  var systolic: Double
  var diastolic: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BloodPressureSample? {
    let startTimestamp = pigeonVar_list[0] as! Int64
    let systolic = pigeonVar_list[1] as! Double
    let diastolic = pigeonVar_list[2] as! Double

    return BloodPressureSample(
      startTimestamp: startTimestamp,
      systolic: systolic,
      diastolic: diastolic
    )
  }
  func toList() -> [Any?] {
    return [
      startTimestamp,
      systolic,
      diastolic,
    ]
  }
  static func == (lhs: BloodPressureSample, rhs: BloodPressureSample) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BloodPressureSamplesResponse: Hashable {
  var samples: [BloodPressureSample]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BloodPressureSamplesResponse? {
    let samples = pigeonVar_list[0] as! [BloodPressureSample]

    return BloodPressureSamplesResponse(
      samples: samples
    )
  }
  func toList() -> [Any?] {
    return [
      samples
    ]
  }
  static func == (lhs: BloodPressureSamplesResponse, rhs: BloodPressureSamplesResponse) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TimestampedValue: Hashable {
  var timestamp: Int64
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TimestampedValue? {
    let timestamp = pigeonVar_list[0] as! Int64
    let value = pigeonVar_list[1] as! Double

    return TimestampedValue(
      timestamp: timestamp,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      timestamp,
      value,
    ]
  }
  static func == (lhs: TimestampedValue, rhs: TimestampedValue) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RoutePoint: Hashable {
  var timestamp: Int64
  var latitude: Double
  var longitude: Double
  var altitude: Double? = nil
  var speed: Double? = nil
  var horizontalAccuracy: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RoutePoint? {
    let timestamp = pigeonVar_list[0] as! Int64
    let latitude = pigeonVar_list[1] as! Double
    let longitude = pigeonVar_list[2] as! Double
    let altitude: Double? = nilOrValue(pigeonVar_list[3])
    let speed: Double? = nilOrValue(pigeonVar_list[4])
    let horizontalAccuracy: Double? = nilOrValue(pigeonVar_list[5])

    return RoutePoint(
      timestamp: timestamp,
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      speed: speed,
      horizontalAccuracy: horizontalAccuracy
    )
  }
  func toList() -> [Any?] {
    return [
      timestamp,
      latitude,
      longitude,
      altitude,
      speed,
      horizontalAccuracy,
    ]
  }
  static func == (lhs: RoutePoint, rhs: RoutePoint) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HeartRateSummary: Hashable {
  var average: Double? = nil
  var min: Double? = nil
  var max: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HeartRateSummary? {
    let average: Double? = nilOrValue(pigeonVar_list[0])
    let min: Double? = nilOrValue(pigeonVar_list[1])
    let max: Double? = nilOrValue(pigeonVar_list[2])

    return HeartRateSummary(
      average: average,
      min: min,
      max: max
    )
  }
  func toList() -> [Any?] {
    return [
      average,
      min,
      max,
    ]
  }
  static func == (lhs: HeartRateSummary, rhs: HeartRateSummary) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Individual activity within a workout.
/// A workout can have multiple activities (e.g., triathlon: swim -> bike -> run).
///
/// Generated class from Pigeon that represents data sent in messages.
struct WorkoutActivity: Hashable {
  var activityType: WorkoutActivityType
  var startTime: Int64
  var endTime: Int64
  var duration: Double
  var locationType: LocationType
  var distance: Double? = nil
  var calories: Double? = nil
  var heartRateSummary: HeartRateSummary? = nil
  var heartRateSamples: [TimestampedValue]? = nil
  var caloriesSamples: [TimestampedValue]? = nil
  var distanceSamples: [TimestampedValue]? = nil
  var routePoints: [RoutePoint]? = nil
  var speedSamples: [TimestampedValue]? = nil
  var cadenceSamples: [TimestampedValue]? = nil
  var powerSamples: [TimestampedValue]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WorkoutActivity? {
    let activityType = pigeonVar_list[0] as! WorkoutActivityType
    let startTime = pigeonVar_list[1] as! Int64
    let endTime = pigeonVar_list[2] as! Int64
    let duration = pigeonVar_list[3] as! Double
    let locationType = pigeonVar_list[4] as! LocationType
    let distance: Double? = nilOrValue(pigeonVar_list[5])
    let calories: Double? = nilOrValue(pigeonVar_list[6])
    let heartRateSummary: HeartRateSummary? = nilOrValue(pigeonVar_list[7])
    let heartRateSamples: [TimestampedValue]? = nilOrValue(pigeonVar_list[8])
    let caloriesSamples: [TimestampedValue]? = nilOrValue(pigeonVar_list[9])
    let distanceSamples: [TimestampedValue]? = nilOrValue(pigeonVar_list[10])
    let routePoints: [RoutePoint]? = nilOrValue(pigeonVar_list[11])
    let speedSamples: [TimestampedValue]? = nilOrValue(pigeonVar_list[12])
    let cadenceSamples: [TimestampedValue]? = nilOrValue(pigeonVar_list[13])
    let powerSamples: [TimestampedValue]? = nilOrValue(pigeonVar_list[14])

    return WorkoutActivity(
      activityType: activityType,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      locationType: locationType,
      distance: distance,
      calories: calories,
      heartRateSummary: heartRateSummary,
      heartRateSamples: heartRateSamples,
      caloriesSamples: caloriesSamples,
      distanceSamples: distanceSamples,
      routePoints: routePoints,
      speedSamples: speedSamples,
      cadenceSamples: cadenceSamples,
      powerSamples: powerSamples
    )
  }
  func toList() -> [Any?] {
    return [
      activityType,
      startTime,
      endTime,
      duration,
      locationType,
      distance,
      calories,
      heartRateSummary,
      heartRateSamples,
      caloriesSamples,
      distanceSamples,
      routePoints,
      speedSamples,
      cadenceSamples,
      powerSamples,
    ]
  }
  static func == (lhs: WorkoutActivity, rhs: WorkoutActivity) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Top-level workout record.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WorkoutRecord: Hashable {
  var id: String
  var sourceName: String
  var sourceBundleId: String? = nil
  var startTime: Int64
  var endTime: Int64
  var duration: Double
  var totalDistance: Double? = nil
  var totalCalories: Double? = nil
  var activities: [WorkoutActivity]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WorkoutRecord? {
    let id = pigeonVar_list[0] as! String
    let sourceName = pigeonVar_list[1] as! String
    let sourceBundleId: String? = nilOrValue(pigeonVar_list[2])
    let startTime = pigeonVar_list[3] as! Int64
    let endTime = pigeonVar_list[4] as! Int64
    let duration = pigeonVar_list[5] as! Double
    let totalDistance: Double? = nilOrValue(pigeonVar_list[6])
    let totalCalories: Double? = nilOrValue(pigeonVar_list[7])
    let activities = pigeonVar_list[8] as! [WorkoutActivity]

    return WorkoutRecord(
      id: id,
      sourceName: sourceName,
      sourceBundleId: sourceBundleId,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      totalDistance: totalDistance,
      totalCalories: totalCalories,
      activities: activities
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      sourceName,
      sourceBundleId,
      startTime,
      endTime,
      duration,
      totalDistance,
      totalCalories,
      activities,
    ]
  }
  static func == (lhs: WorkoutRecord, rhs: WorkoutRecord) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WorkoutQueryRequest: Hashable {
  var startTimestamp: Int64
  var endTimestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WorkoutQueryRequest? {
    let startTimestamp = pigeonVar_list[0] as! Int64
    let endTimestamp: Int64? = nilOrValue(pigeonVar_list[1])

    return WorkoutQueryRequest(
      startTimestamp: startTimestamp,
      endTimestamp: endTimestamp
    )
  }
  func toList() -> [Any?] {
    return [
      startTimestamp,
      endTimestamp,
    ]
  }
  static func == (lhs: WorkoutQueryRequest, rhs: WorkoutQueryRequest) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WorkoutQueryResponse: Hashable {
  var workouts: [WorkoutRecord]
  var lastSyncTimestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WorkoutQueryResponse? {
    let workouts = pigeonVar_list[0] as! [WorkoutRecord]
    let lastSyncTimestamp: Int64? = nilOrValue(pigeonVar_list[1])

    return WorkoutQueryResponse(
      workouts: workouts,
      lastSyncTimestamp: lastSyncTimestamp
    )
  }
  func toList() -> [Any?] {
    return [
      workouts,
      lastSyncTimestamp,
    ]
  }
  static func == (lhs: WorkoutQueryResponse, rhs: WorkoutQueryResponse) -> Bool {
    return deepEqualsAppleHealthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleHealthMessages(value: toList(), hasher: &hasher)
  }
}

private class AppleHealthMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AppleHealthDataType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AppleHealthAuthorizationResult(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AppleHealthReadRequestStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AppleHealthSleepStageType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WorkoutActivityType(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LocationType(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return AppleHealthAuthorizationResponse.fromList(self.readValue() as! [Any?])
    case 136:
      return HealthStatistics.fromList(self.readValue() as! [Any?])
    case 137:
      return HealthSample.fromList(self.readValue() as! [Any?])
    case 138:
      return HealthQueryRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return HealthStatisticsResponse.fromList(self.readValue() as! [Any?])
    case 140:
      return HealthSamplesResponse.fromList(self.readValue() as! [Any?])
    case 141:
      return SleepSample.fromList(self.readValue() as! [Any?])
    case 142:
      return SleepQueryRequest.fromList(self.readValue() as! [Any?])
    case 143:
      return SleepSamplesResponse.fromList(self.readValue() as! [Any?])
    case 144:
      return BloodPressureSample.fromList(self.readValue() as! [Any?])
    case 145:
      return BloodPressureSamplesResponse.fromList(self.readValue() as! [Any?])
    case 146:
      return TimestampedValue.fromList(self.readValue() as! [Any?])
    case 147:
      return RoutePoint.fromList(self.readValue() as! [Any?])
    case 148:
      return HeartRateSummary.fromList(self.readValue() as! [Any?])
    case 149:
      return WorkoutActivity.fromList(self.readValue() as! [Any?])
    case 150:
      return WorkoutRecord.fromList(self.readValue() as! [Any?])
    case 151:
      return WorkoutQueryRequest.fromList(self.readValue() as! [Any?])
    case 152:
      return WorkoutQueryResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AppleHealthMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppleHealthDataType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AppleHealthAuthorizationResult {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AppleHealthReadRequestStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? AppleHealthSleepStageType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? WorkoutActivityType {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocationType {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? AppleHealthAuthorizationResponse {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? HealthStatistics {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? HealthSample {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? HealthQueryRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? HealthStatisticsResponse {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? HealthSamplesResponse {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? SleepSample {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? SleepQueryRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? SleepSamplesResponse {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? BloodPressureSample {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? BloodPressureSamplesResponse {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? TimestampedValue {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? RoutePoint {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? HeartRateSummary {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? WorkoutActivity {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? WorkoutRecord {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? WorkoutQueryRequest {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? WorkoutQueryResponse {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AppleHealthMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AppleHealthMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AppleHealthMessagesPigeonCodecWriter(data: data)
  }
}

class AppleHealthMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AppleHealthMessagesPigeonCodec(readerWriter: AppleHealthMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppleHealthHostApi {
  func isAvailable() throws -> Bool
  func requestReadAuthorization(dataTypes: [AppleHealthDataType], completion: @escaping (Result<AppleHealthAuthorizationResponse, Error>) -> Void)
  /// Non-prompting check of whether HealthKit would still present its
  /// authorization sheet for [dataTypes] (i.e. whether the app has ever
  /// requested them). Backed by
  /// `HKHealthStore.getRequestStatusForAuthorization(toShare:read:)`. Lets a
  /// headless caller fail fast instead of silently reading no data when the app
  /// was never authorized.
  func getReadRequestStatus(dataTypes: [AppleHealthDataType], completion: @escaping (Result<AppleHealthReadRequestStatus, Error>) -> Void)
  func openHealthSettings(completion: @escaping (Result<Void, Error>) -> Void)
  /// Throws FlutterError on failure.
  func queryStatistics(request: HealthQueryRequest, completion: @escaping (Result<HealthStatisticsResponse, Error>) -> Void)
  /// Throws FlutterError on failure.
  func querySamples(request: HealthQueryRequest, completion: @escaping (Result<HealthSamplesResponse, Error>) -> Void)
  /// Throws FlutterError on failure.
  func querySleepSamples(request: SleepQueryRequest, completion: @escaping (Result<SleepSamplesResponse, Error>) -> Void)
  /// Throws FlutterError on failure.
  func queryBloodPressureSamples(request: SleepQueryRequest, completion: @escaping (Result<BloodPressureSamplesResponse, Error>) -> Void)
  /// Queries workouts newer than startTimestamp.
  /// Returns workout data with associated samples (HR, steps, calories, route, cycling data).
  /// Throws FlutterError on failure.
  func queryWorkouts(request: WorkoutQueryRequest, completion: @escaping (Result<WorkoutQueryResponse, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppleHealthHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AppleHealthMessagesPigeonCodec.shared }
  /// Sets up an instance of `AppleHealthHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppleHealthHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    let requestReadAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.requestReadAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestReadAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataTypesArg = args[0] as! [AppleHealthDataType]
        api.requestReadAuthorization(dataTypes: dataTypesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestReadAuthorizationChannel.setMessageHandler(nil)
    }
    /// Non-prompting check of whether HealthKit would still present its
    /// authorization sheet for [dataTypes] (i.e. whether the app has ever
    /// requested them). Backed by
    /// `HKHealthStore.getRequestStatusForAuthorization(toShare:read:)`. Lets a
    /// headless caller fail fast instead of silently reading no data when the app
    /// was never authorized.
    let getReadRequestStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.getReadRequestStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getReadRequestStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataTypesArg = args[0] as! [AppleHealthDataType]
        api.getReadRequestStatus(dataTypes: dataTypesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getReadRequestStatusChannel.setMessageHandler(nil)
    }
    let openHealthSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.openHealthSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openHealthSettingsChannel.setMessageHandler { _, reply in
        api.openHealthSettings { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openHealthSettingsChannel.setMessageHandler(nil)
    }
    /// Throws FlutterError on failure.
    let queryStatisticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.queryStatistics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryStatisticsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HealthQueryRequest
        api.queryStatistics(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryStatisticsChannel.setMessageHandler(nil)
    }
    /// Throws FlutterError on failure.
    let querySamplesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.querySamples\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      querySamplesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HealthQueryRequest
        api.querySamples(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      querySamplesChannel.setMessageHandler(nil)
    }
    /// Throws FlutterError on failure.
    let querySleepSamplesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.querySleepSamples\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      querySleepSamplesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SleepQueryRequest
        api.querySleepSamples(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      querySleepSamplesChannel.setMessageHandler(nil)
    }
    /// Throws FlutterError on failure.
    let queryBloodPressureSamplesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.queryBloodPressureSamples\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryBloodPressureSamplesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SleepQueryRequest
        api.queryBloodPressureSamples(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryBloodPressureSamplesChannel.setMessageHandler(nil)
    }
    /// Queries workouts newer than startTimestamp.
    /// Returns workout data with associated samples (HR, steps, calories, route, cycling data).
    /// Throws FlutterError on failure.
    let queryWorkoutsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_health.AppleHealthHostApi.queryWorkouts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryWorkoutsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! WorkoutQueryRequest
        api.queryWorkouts(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryWorkoutsChannel.setMessageHandler(nil)
    }
  }
}
